apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  index.html: PCFET0NUWVBFIGh0bWw+CjxodG1sPgogICAgPGJvZHk+CiAgICAgICAgPGgxIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOkRvZGdlckJsdWU7Ij5IZWxsbyBXb3JsZCEhPC9oMT4KICAgIDwvYm9keT4KPC9odG1sPgoKCg==
