apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    release: {{ .Values.deploymentName }}
spec:
  selector:
    release: {{ .Values.deploymentName }}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
